all: timer_create timer_create_evp_null

timer_create: timer_create.c
	gcc timer_create.c -o timer_create -Wall -lrt

timer_create_evp_null: timer_create_evp_null.c
	gcc timer_create_evp_null.c -o timer_create_evp_null -Wall -lrt
